HELP_TEXT = (
    "Right now I can help you with:\n"
    "1. Analyze account — e.g. `Actus, analyze account SGP`\n"
    "2. Analyze ticket — e.g. `Actus, analyze ticket R-058284`\n"
    "3. Analyze item — e.g. `Actus, analyze item 1007986`\n"
    "4. Ticket status — e.g. `Actus, status on ticket R-048484`\n"
    "5. Record lookup — e.g. `Actus, is ticket R-040699 logged in the system?` "
    "or `Actus, do we have invoice 14068709 on record?`\n"
    "6. Customer history — e.g. `Actus, show all tickets for customer YAM in last 30 days`\n"
    "7. Mixed lines — e.g. `Actus, show mixed lines`\n"
    "8. Credit activity — e.g. `Actus, how many credits did I update from Nov 1st to today?`\n"
    "9. Credits with RTN — e.g. `Actus, how many credits have a credit number?`\n"
    "10. Priority tickets — e.g. `Actus, what tickets are priority right now?`\n"
    "11. Credit aging — e.g. `Actus, show the credit aging summary` or "
    "`Actus, show credits over 60 days`\n"
    "12. Stalled tickets — e.g. `Actus, which tickets haven't been updated in 7 days?`\n"
    "13. Overall overview — e.g. `Actus, give me a credit overview`\n"
    "14. Root causes — e.g. `Actus, summarize credit totals by root cause`\n"
    "15. Top accounts — e.g. `Actus, which accounts have the most credits?`\n"
    "16. Top sales reps — e.g. `Actus, which sales reps have the most credits?`\n"
    "17. Top items — e.g. `Actus, which items have the most credits issued?`\n"
    "18. Credit trends — e.g. `Actus, are there any credit trends worth sharing?`\n"
    "19. Anomalies — e.g. `Actus, any unusual or suspicious credits lately?`\n"
    "20. Investigation notes — e.g. `Actus, show investigation notes for ticket R-053805`\n"
    "21. System updates with RTN — e.g. `Actus, show system-updated records with RTN`\n"
    "22. Credit ops snapshot — e.g. `Actus, provide the credit ops snapshot between 2025-01-01 and 2025-03-31`\n"
    "23. Credit amount chart — e.g. `Actus, plot credit amounts between 2025-01-01 and 2025-12-31`\n"
    "24. Bulk search — e.g. `Actus, bulk search invoices: 14068709, 14068710` "
    "or `Actus, bulk lookup customer numbers: YAM, LUX`\n"
)
